### ISSUE TITLE
Could not login with valid credentials

### ISSUE THREAD

**Issue by nitnelave** [Gwindow/WhatAndroid#33]
Hello,

I just installed the WhatAndroid app, that I directly downloaded from github (v2.1.3 Beta).
I input my credentials (login/pass), but it said "Could not login". I tried the same on my computer, with success. I'm quite sure I typed the password right, I did it 3 times.

Any idea?

Thanks,

**Comment by Twinklebear** [comment]
Other users have reported this and unfortunately I've never been able to reproduce it on my phone or in the emulator so I'm not sure what the cause of the issue is. Some people who have had this issue found that restarting their phone resolved it, so give that a try and let me know how it works out.

Sorry about the trouble, this bug has been kind of a mystery nuisance for a while now.

**Comment by nitnelave** [comment]
Thank you for your answer.

Rebooting might have helped, but I think what did the trick was removing
the space android added at the end of the login (when using
autocompletion)...

Sorry for opening an issue over that, it works now!

Thanks

**Comment by Twinklebear** [comment]
Cool, good to hear it's working now :smile:
